services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trip-optimizer-backend
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-8000} --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trip-optimizer-network

  # Storage API Service
  storage-api:
    build:
      context: ./storage-api
      dockerfile: Dockerfile
    container_name: trip-optimizer-storage-api
    ports:
      - "${STORAGE_API_PORT:-8001}:${STORAGE_API_PORT:-8001}"
    env_file:
      - ./storage-api/.env
    volumes:
      - ./storage-api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${STORAGE_API_PORT:-8001} --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${STORAGE_API_PORT:-8001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trip-optimizer-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trip-optimizer-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trip-optimizer-network

networks:
  trip-optimizer-network:
    driver: bridge